name: Zip Europa Universalis IV mod
description: >
  Create an extract-and-play zip archive of an Europa Universalis IV mod.
author: maxice8

branding:
  color: yellow
  icon: archive

inputs:
  mod-name:
    required: false
    description: >
      Name of the mod, if not provided reads from descriptor.mod,
      if set replaces the name in the descriptor.mod.
  descriptor-name:
    required: false
    description: >
      Name of the .mod descriptor file, overrides mod-name.
      Defaults to the name of the mod if not present.
  zip-name:
    required: false
    default: ''
    description: >
      Final name of the zip file.
      Defaults to the name of the mod if not present.
  prefix-name:
    required: false
    default: ''
    description: >
      Name of the prefix directory.
      Defaults to the name of the mod if not present.

outputs:
  zip-path:
    description: >
      Path to the created zip archive
    value: ${{ steps.zip.outputs.zip-path }}

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - name: zip
      id: zip
      env:
        MOD_NAME: ${{ inputs.mod-name }}
        DESCRIPTOR_NAME: ${{ inputs.descriptor-name }}
        ZIP_NAME: ${{ inputs.zip-name }}
        PREFIX_NAME: ${{ inputs.prefix-name }}

      run: ${{ github.action_path }}/mkzip.sh
      shell: bash
